version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongo-server
    expose:
      - '27017'
    ports:
      - '27017:27017'
    volumes:
      - 'mongodata:/data/db'
      - '/d/mongodb/configdb:/data/configdb'
    command: mongod --auth
    tty: true
    privileged: true
    restart: always
    networks:
      - local-net
networks:
  local-net:
    external: true
volumes:
  mongodata:
    external: true
